name: CI/CD Pipeline

# When this workflow runs: on pushes to main and all pull requests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Environment variables available to all jobs
env:
  NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
  NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key
  NEXT_PUBLIC_APP_URL: http://localhost:3001

jobs:
  # Job 1: Unit & Integration Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start Supabase (local database for tests)
        run: |
          npx supabase start
          
      - name: Run unit and integration tests
        run: npm run test
        
      - name: Stop Supabase
        run: npx supabase stop --no-backup

  # Job 2: End-to-End Tests
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start Supabase
        run: npx supabase start
        
      - name: Build application
        run: npm run build
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run E2E tests
        run: npm run test:e2e
        
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-results
          path: test-results/
          
      - name: Stop Supabase
        run: npx supabase stop --no-backup

  # Job 3: Visual Regression Tests
  visual:
    name: Visual Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start Supabase
        run: npx supabase start
        
      - name: Build application
        run: npm run build
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run visual regression tests
        run: npm run test:visual
        
      - name: Upload visual test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: visual-test-results
          path: test-results/
          
      - name: Stop Supabase
        run: npx supabase stop --no-backup

  # Job 4: Deploy to Vercel (only on main branch pushes)
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: [test, e2e, visual]  # Only deploy if all tests pass
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'